# Generated by Django 2.0.2 on 2018-02-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_types', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='field_types.FieldType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
