# Generated by Django 2.0.1 on 2018-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20180211_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='field',
            name='required',
            field=models.NullBooleanField(),
        ),
    ]
