# Generated by Django 2.0.2 on 2018-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
