# Generated by Django 2.0.2 on 2018-02-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risks', '0001_initial'),
        ('fields', '0002_auto_20180211_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldByRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Risk')),
            ],
        ),
    ]
