# Generated by Django 2.0.1 on 2018-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields_by_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldbyrisk',
            name='value',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
